
    create table billing (
        amount_tva numeric(10,2) not null,
        billing_date date not null,
        discount numeric(10,2),
        sub_total numeric(10,2) not null,
        total_price numeric(10,2) not null,
        client_id bigint not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        reference varchar(30) not null unique,
        state varchar(255) not null check ((state in ('BROUILLON','VALIDEE','PAYEE','ANNULEE'))),
        primary key (id)
    );

    create table billing_line (
        quantity integer not null,
        total_line_price numeric(10,2) not null,
        tva_amount numeric(10,2) not null,
        tva_rate float(53) not null,
        unit_price numeric(10,2) not null,
        billing_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name varchar(100) not null unique,
        primary key (id)
    );

    create table client (
        archived boolean not null,
        id bigint generated by default as identity,
        email varchar(100) not null unique,
        name varchar(100) not null,
        phone varchar(100) not null,
        primary key (id)
    );

    create table client_address (
        client_id bigint not null,
        locality varchar(100) not null,
        postal_code varchar(100) not null,
        street varchar(100) not null,
        number varchar(255) not null,
        type varchar(255) not null check ((type in ('FACTURATION','LIVRAISON'))),
        primary key (client_id, locality, postal_code, street, number, type)
    );

    create table company (
        id bigint generated by default as identity,
        email varchar(100) not null,
        iban varchar(100) not null,
        locality varchar(100) not null,
        name varchar(100) not null,
        phone varchar(100) not null,
        postal_code varchar(100) not null,
        street varchar(100) not null,
        tva_number varchar(100) not null,
        number varchar(255) not null,
        primary key (id)
    );

    create table payment (
        amount numeric(10,2) not null,
        payment_date date not null,
        billing_id bigint not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        payment_method varchar(255) not null check ((payment_method in ('VIREMENT','CARTE','ESPECE','CHEQUE'))),
        primary key (id)
    );

    create table product (
        archived boolean not null,
        min_stock_quantity integer not null,
        purchase_price numeric(10,2) not null,
        selling_price numeric(10,2) not null,
        tva_rate float(53) not null,
        category_id bigint not null,
        id bigint generated by default as identity,
        reference varchar(30) not null unique,
        name varchar(100) not null,
        description varchar(250),
        primary key (id)
    );

    create table purchase_order (
        date date not null,
        total_price numeric(10,2) not null,
        id bigint generated by default as identity,
        supplier_id bigint not null,
        user_id bigint not null,
        reference varchar(30) not null unique,
        state varchar(255) not null check ((state in ('EN_ATTENTE','RECUE','ANNULEE'))),
        primary key (id)
    );

    create table purchase_order_line (
        quantity integer not null,
        unit_price numeric(10,2) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        purchase_order_id bigint not null,
        primary key (id)
    );

    create table quote (
        amount_tva numeric(10,2) not null,
        discount numeric(10,2),
        expiration_date date not null,
        quote_date date not null,
        sub_total numeric(10,2) not null,
        total_price numeric(10,2) not null,
        billing_id bigint unique,
        client_id bigint not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        reference varchar(30) not null unique,
        state varchar(255) not null check ((state in ('BROUILLON','ENVOYE','ACCEPTE','REFUSE'))),
        primary key (id)
    );

    create table quote_line (
        quantity integer not null,
        total_line_price numeric(10,2) not null,
        tva_amount numeric(10,2) not null,
        tva_rate float(53) not null,
        unit_price numeric(10,2) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        quote_id bigint not null,
        primary key (id)
    );

    create table reference_counter (
        last_number integer not null,
        year integer not null,
        id bigint generated by default as identity,
        prefix varchar(10),
        primary key (id),
        unique (year, prefix)
    );

    create table stock_movement (
        quantity integer not null,
        billing_id bigint,
        id bigint generated by default as identity,
        movement_date timestamp(6) not null,
        product_id bigint not null,
        purchase_order_id bigint,
        user_id bigint not null,
        type varchar(255) not null check ((type in ('ENTREE','SORTIE','AJUSTEMENT_POSITIF','AJUSTEMENT_NEGATIF','RETOUR_CLIENT'))),
        primary key (id)
    );

    create table supplier (
        archived boolean not null,
        id bigint generated by default as identity,
        email varchar(100) not null unique,
        locality varchar(100) not null,
        name varchar(100) not null,
        phone varchar(100) not null,
        postal_code varchar(100) not null,
        street varchar(100) not null,
        number varchar(255) not null,
        primary key (id)
    );

    create table user_ (
        archived boolean not null,
        id bigint generated by default as identity,
        email varchar(100) not null unique,
        name varchar(100) not null,
        password varchar(100) not null,
        role varchar(255) not null check ((role in ('ADMIN','EMPLOYEE'))),
        primary key (id)
    );

    alter table if exists billing 
       add constraint FK6gcofkcn2y7iaw1yfq3wt2rxr 
       foreign key (client_id) 
       references client;

    alter table if exists billing 
       add constraint FKndji7ynueewp1gjx4ruarjf8f 
       foreign key (user_id) 
       references user_;

    alter table if exists billing_line 
       add constraint FKgbdmhi0h2rx8dknqlh2q87wus 
       foreign key (billing_id) 
       references billing;

    alter table if exists billing_line 
       add constraint FKcwkrg71dnyk0gfxt2d47fb7lj 
       foreign key (product_id) 
       references product;

    alter table if exists client_address 
       add constraint FK8syw6n1lu2fspywj86fumxb9i 
       foreign key (client_id) 
       references client;

    alter table if exists payment 
       add constraint FKe6nyre8vw8o0iimne80k9kqlr 
       foreign key (billing_id) 
       references billing;

    alter table if exists payment 
       add constraint FKf0pg83y5tcuskkc3xjih90n1n 
       foreign key (user_id) 
       references user_;

    alter table if exists product 
       add constraint FK1mtsbur82frn64de7balymq9s 
       foreign key (category_id) 
       references category;

    alter table if exists purchase_order 
       add constraint FK4traogu3jriq9u7e8rvm86k7i 
       foreign key (supplier_id) 
       references supplier;

    alter table if exists purchase_order 
       add constraint FKqxltadltnk6wenu8xvrbd95cy 
       foreign key (user_id) 
       references user_;

    alter table if exists purchase_order_line 
       add constraint FKay5qxwi9g9fnlwc8ijxkxqqas 
       foreign key (product_id) 
       references product;

    alter table if exists purchase_order_line 
       add constraint FK210t80fsgdi4s4g7tlg9vdgkd 
       foreign key (purchase_order_id) 
       references purchase_order;

    alter table if exists quote 
       add constraint FKpeleao36rm2i53jukoujp4gb6 
       foreign key (billing_id) 
       references billing;

    alter table if exists quote 
       add constraint FKau0dqte125fn24anh3k8014eu 
       foreign key (client_id) 
       references client;

    alter table if exists quote 
       add constraint FK18xxd4xt1o5p685j5t8pjgdnw 
       foreign key (user_id) 
       references user_;

    alter table if exists quote_line 
       add constraint FKc3g6f3c5rj6ntjc7gu76l6c4x 
       foreign key (product_id) 
       references product;

    alter table if exists quote_line 
       add constraint FKnbxr28wot0665o7o2fgy4h0xr 
       foreign key (quote_id) 
       references quote;

    alter table if exists stock_movement 
       add constraint FKhev38pisyy4he2pse9078nfyp 
       foreign key (billing_id) 
       references billing;

    alter table if exists stock_movement 
       add constraint FKq63e7y5l2pnh2tt2lvxlquvbf 
       foreign key (product_id) 
       references product;

    alter table if exists stock_movement 
       add constraint FKlwduxrb7voq86usyv2w5dhqvh 
       foreign key (purchase_order_id) 
       references purchase_order;

    alter table if exists stock_movement 
       add constraint FKqcn0wb022wf3x4bmcnif0yq6k 
       foreign key (user_id) 
       references user_;
